fragment ProductsParts on Products {
  __typename
  title
  slug
  price
  badge
  image
  inStock
  seoTitle
  seoDescription
  features
  specs {
    __typename
    color
    dimensions
    weight
    connection
    warranty
  }
  boxContents
  relatedProducts
  body
}

fragment ReviewsParts on Reviews {
  __typename
  author
  rating
  body
}

fragment PagesParts on Pages {
  __typename
  slug
  title
  body
}
